#Exploartory Data Analaysis

##Importing Necessary Libraries

In [146]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
plt.style.use('ggplot')
pd.set_option('display.max_columns', 200)

##Reading Csv File

In [147]:
df = pd.read_csv(r'/Users/asan/archive/coaster_db.csv')

In [148]:
df.head()

,coaster_name,Length,Speed,Location,Status,Opening date,Type,Manufacturer,Height restriction,Model,Height,Inversions,Lift/launch system,Cost,Trains,Park section,Duration,Capacity,G-force,Designer,Max vertical angle,Drop,Soft opening date,Fast Lane available,Replaced,Track layout,Fastrack available,Soft opening date.1,Closing date,Opened,Replaced by,Website,Flash Pass Available,Must transfer from wheelchair,Theme,Single rider line available,Restraint Style,Flash Pass available,Acceleration,Restraints,Name,year_introduced,latitude,longitude,Type_Main,opening_date_clean,speed1,speed2,speed1_value,speed1_unit,speed_mph,height_value,height_unit,height_ft,Inversions_clean,Gforce_clean
0,Switchback Railway,600 ft (180 m),6 mph (9.7 km/h),Coney Island,Removed,"June 16, 1884",Wood,LaMarcus Adna Thompson,NaN,Lift Packed,50 ft (15 m),NaN,gravity,NaN,NaN,Coney Island Cyclone Site,1:00,1600 riders per hour,2.9,LaMarcus Adna Thompson,30°,43 ft (13 m),NaN,NaN,NaN,Gravity pulled coaster,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1884,40.5740,-73.9780,Wood,1884-06-16,6 mph,9.7 km/h,6.0,mph,6.0,50.0,ft,NaN,0,2.9
1,Flip Flap Railway,NaN,NaN,Sea Lion Park,Removed,1895,Wood,Lina Beecher,NaN,NaN,NaN,1.0,NaN,NaN,a single car. Riders are arranged 1 across in ...,NaN,NaN,NaN,12,Lina Beecher,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1902,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1895,40.5780,-73.9790,Wood,1895-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,12.0
2,Switchback Railway (Euclid Beach Park),NaN,NaN,"Cleveland, Ohio, United States",Closed,NaN,Other,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1895,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1896,41.5800,-81.5700,Other,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
3,Loop the Loop (Coney Island),NaN,NaN,Other,Removed,1901,Steel,Edwin Prescott,NaN,NaN,NaN,1.0,NaN,NaN,a single car. Riders are arranged 2 across in ...,NaN,NaN,NaN,NaN,Edward A. Green,NaN,NaN,NaN,NaN,Switchback Railway,NaN,NaN,NaN,1910,NaN,Giant Racer,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1901,40.5745,-73.9780,Steel,1901-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN
4,Loop the Loop (Young's Pier),NaN,NaN,Other,Removed,1901,Steel,Edwin Prescott,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Edward A. Green,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1912,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1901,39.3538,-74.4342,Steel,1901-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN

##Task_1: Selecting Columns Needed

In [149]:
df.columns

Index(['coaster_name', 'Length', 'Speed', 'Location', 'Status', 'Opening date',
       'Type', 'Manufacturer', 'Height restriction', 'Model', 'Height',
       'Inversions', 'Lift/launch system', 'Cost', 'Trains', 'Park section',
       'Duration', 'Capacity', 'G-force', 'Designer', 'Max vertical angle',
       'Drop', 'Soft opening date', 'Fast Lane available', 'Replaced',
       'Track layout', 'Fastrack available', 'Soft opening date.1',
       'Closing date', 'Opened', 'Replaced by', 'Website',
       'Flash Pass Available', 'Must transfer from wheelchair', 'Theme',
       'Single rider line available', 'Restraint Style',
       'Flash Pass available', 'Acceleration', 'Restraints', 'Name',
       'year_introduced', 'latitude', 'longitude', 'Type_Main',
       'opening_date_clean', 'speed1', 'speed2', 'speed1_value', 'speed1_unit',
       'speed_mph', 'height_value', 'height_unit', 'height_ft',
       'Inversions_clean', 'Gforce_clean'],
      dtype='object')

###Way_1 : Subseting Columns

In [150]:
 df = df[['coaster_name', 
    #'Length', 'Speed', 
    'Location', 'Status', 
    'Opening date',
      # 'Type', ''
       'Manufacturer', 
       #'Height restriction', 'Model', 'Height',
       #'Inversions', 'Lift/launch system', 'Cost', 'Trains', 'Park section',
       #'Duration', 'Capacity', 'G-force', 'Designer', 'Max vertical angle',
       #'Drop', 'Soft opening date', 'Fast Lane available', 'Replaced',
       #'Track layout', 'Fastrack available', 'Soft opening date.1',
       #'Closing date', 'Opened', 'Replaced by', 'Website',
       #'Flash Pass Available', 'Must transfer from wheelchair', 'Theme',
       #'Single rider line available', 'Restraint Style',
       #'Flash Pass available', 'Acceleration', 'Restraints', 'Name',
       'year_introduced', 'latitude', 'longitude', 'Type_Main',
       'opening_date_clean', 
       #'speed1', 'speed2', 'speed1_value', 'speed1_unit',
       'speed_mph', 
       #'height_value', 'height_unit', 
       'height_ft',
       'Inversions_clean', 'Gforce_clean']].copy()

In [151]:
df.head()

,coaster_name,Location,Status,Opening date,Manufacturer,year_introduced,latitude,longitude,Type_Main,opening_date_clean,speed_mph,height_ft,Inversions_clean,Gforce_clean
0,Switchback Railway,Coney Island,Removed,"June 16, 1884",LaMarcus Adna Thompson,1884,40.5740,-73.9780,Wood,1884-06-16,6.0,NaN,0,2.9
1,Flip Flap Railway,Sea Lion Park,Removed,1895,Lina Beecher,1895,40.5780,-73.9790,Wood,1895-01-01,NaN,NaN,1,12.0
2,Switchback Railway (Euclid Beach Park),"Cleveland, Ohio, United States",Closed,NaN,NaN,1896,41.5800,-81.5700,Other,NaN,NaN,NaN,0,NaN
3,Loop the Loop (Coney Island),Other,Removed,1901,Edwin Prescott,1901,40.5745,-73.9780,Steel,1901-01-01,NaN,NaN,1,NaN
4,Loop the Loop (Young's Pier),Other,Removed,1901,Edwin Prescott,1901,39.3538,-74.4342,Steel,1901-01-01,NaN,NaN,1,NaN

###Way_2: Dropping the columns

In [152]:
# df = df.drop(['Opening date'], axis = 1)

In [153]:
df.columns

Index(['coaster_name', 'Location', 'Status', 'Opening date', 'Manufacturer',
       'year_introduced', 'latitude', 'longitude', 'Type_Main',
       'opening_date_clean', 'speed_mph', 'height_ft', 'Inversions_clean',
       'Gforce_clean'],
      dtype='object')

In [154]:
df.shape

(1087, 14)

In [155]:
df.head()

,coaster_name,Location,Status,Opening date,Manufacturer,year_introduced,latitude,longitude,Type_Main,opening_date_clean,speed_mph,height_ft,Inversions_clean,Gforce_clean
0,Switchback Railway,Coney Island,Removed,"June 16, 1884",LaMarcus Adna Thompson,1884,40.5740,-73.9780,Wood,1884-06-16,6.0,NaN,0,2.9
1,Flip Flap Railway,Sea Lion Park,Removed,1895,Lina Beecher,1895,40.5780,-73.9790,Wood,1895-01-01,NaN,NaN,1,12.0
2,Switchback Railway (Euclid Beach Park),"Cleveland, Ohio, United States",Closed,NaN,NaN,1896,41.5800,-81.5700,Other,NaN,NaN,NaN,0,NaN
3,Loop the Loop (Coney Island),Other,Removed,1901,Edwin Prescott,1901,40.5745,-73.9780,Steel,1901-01-01,NaN,NaN,1,NaN
4,Loop the Loop (Young's Pier),Other,Removed,1901,Edwin Prescott,1901,39.3538,-74.4342,Steel,1901-01-01,NaN,NaN,1,NaN

In [156]:
df.dtypes

coaster_name           object
Location               object
Status                 object
Opening date           object
Manufacturer           object
year_introduced         int64
latitude              float64
longitude             float64
Type_Main              object
opening_date_clean     object
speed_mph             float64
height_ft             float64
Inversions_clean        int64
Gforce_clean          float64
dtype: object

##Task_2: Conveeting dtypes in columns

In [157]:
df['opening_date_clean'] = pd.to_datetime(df['opening_date_clean'], format='%Y-%m-%d', errors='coerce')

In [158]:
#pd.numeric(['column_name'], errors='coerce')

In [159]:
df.head()

,coaster_name,Location,Status,Opening date,Manufacturer,year_introduced,latitude,longitude,Type_Main,opening_date_clean,speed_mph,height_ft,Inversions_clean,Gforce_clean
0,Switchback Railway,Coney Island,Removed,"June 16, 1884",LaMarcus Adna Thompson,1884,40.5740,-73.9780,Wood,1884-06-16,6.0,NaN,0,2.9
1,Flip Flap Railway,Sea Lion Park,Removed,1895,Lina Beecher,1895,40.5780,-73.9790,Wood,1895-01-01,NaN,NaN,1,12.0
2,Switchback Railway (Euclid Beach Park),"Cleveland, Ohio, United States",Closed,NaN,NaN,1896,41.5800,-81.5700,Other,NaT,NaN,NaN,0,NaN
3,Loop the Loop (Coney Island),Other,Removed,1901,Edwin Prescott,1901,40.5745,-73.9780,Steel,1901-01-01,NaN,NaN,1,NaN
4,Loop the Loop (Young's Pier),Other,Removed,1901,Edwin Prescott,1901,39.3538,-74.4342,Steel,1901-01-01,NaN,NaN,1,NaN

##Day_2

In [160]:
df['opening_date_clean']

0      1884-06-16
1      1895-01-01
2             NaT
3      1901-01-01
4      1901-01-01
          ...
1082          NaT
1083   2022-01-01
1084   2016-06-16
1085          NaT
1086   2022-01-01
Name: opening_date_clean, Length: 1087, dtype: datetime64[ns]

##Task_2_Dropping_Rows_with_duplicates

In [161]:
df.columns

Index(['coaster_name', 'Location', 'Status', 'Opening date', 'Manufacturer',
       'year_introduced', 'latitude', 'longitude', 'Type_Main',
       'opening_date_clean', 'speed_mph', 'height_ft', 'Inversions_clean',
       'Gforce_clean'],
      dtype='object')

##Task_3_Rename_the_columns

In [162]:
df = df.rename(columns={'opening_date_clean': 'opening_date',
                   'Inversions_clean':'Inversions',
                   'Gforce_clean':'G-force'}, )

###Finding duplicated on specific columns

In [163]:
df.loc[df.duplicated(subset=['coaster_name'])]

,coaster_name,Location,Status,Opening date,Manufacturer,year_introduced,latitude,longitude,Type_Main,opening_date,speed_mph,height_ft,Inversions,G-force
43,Crystal Beach Cyclone,Crystal Beach Park,Removed,1926,Traver Engineering,1927,42.8617,-79.0598,Wood,1926-01-01,60.0,NaN,0,4.0
60,Derby Racer,Revere Beach,Removed,1911,Fred W. Pearce,1937,42.4200,-70.9860,Wood,1911-01-01,NaN,NaN,0,NaN
61,Blue Streak (Conneaut Lake),Conneaut Lake Park,Closed,"May 23, 1938",NaN,1938,41.6349,-80.3180,Wood,1938-05-23,50.0,NaN,0,NaN
167,Big Thunder Mountain Railroad,Other,NaN,NaN,Arrow Development (California and Florida)Dyna...,1980,NaN,NaN,Steel,NaT,35.0,NaN,0,NaN
237,Thunder Run (Canada's Wonderland),Canada's Wonderland,Operating,"May 23, 1981 as Blauer Enzian, 1986 as Thunder...",Mack Rides,1986,43.8427,-79.5423,Steel,1981-05-23,39.8,32.8,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1063,Lil' Devil Coaster,Six Flags Great Adventure,Operating,1999 as Road Runner Railway; 2021 as Lil' Devi...,Zamperla,2021,40.1343,-74.4434,Steel,1999-01-01,NaN,NaN,0,NaN
1064,Little Dipper (Conneaut Lake Park),Conneaut Lake Park,Operating,1950s,Allan Herschell Company,2021,41.6343,-80.3165,Steel,1950-01-01,NaN,NaN,0,NaN
1080,Iron Gwazi,Busch Gardens Tampa Bay,Under construction,NaN,Rocky Mountain Construction,2022,28.0339,-82.4231,Steel,NaT,76.0,NaN,2,NaN
1082,American Dreier Looping,Other,NaN,NaN,Anton Schwarzkopf,2022,NaN,NaN,Steel,NaT,53.0,NaN,3,4.7
1084,Tron Lightcycle Power Run,Other,NaN,"June 16, 2016",Vekoma,2022,NaN,NaN,Steel,2016-06-16,59.3,NaN,0,4.0

In [164]:
df.query("coaster_name == 'Derby Racer'")

,coaster_name,Location,Status,Opening date,Manufacturer,year_introduced,latitude,longitude,Type_Main,opening_date,speed_mph,height_ft,Inversions,G-force
14,Derby Racer,Revere Beach,Removed,1911,Fred W. Pearce,1911,42.42,-70.986,Wood,1911-01-01,NaN,NaN,0,NaN
60,Derby Racer,Revere Beach,Removed,1911,Fred W. Pearce,1937,42.42,-70.986,Wood,1911-01-01,NaN,NaN,0,NaN

In [165]:
df = df.loc[~df.duplicated(subset='coaster_name')] \
        .reset_index(drop=True)

In [166]:
df.shape

(990, 14)

In [145]:
df.columns

Index(['coaster_name', 'Location', 'Status', 'Opening date', 'Manufacturer',
       'year_introduced', 'latitude', 'longitude', 'Type_Main', 'opening_date',
       'speed_mph', 'height_ft', 'Inversions', 'G-force'],
      dtype='object')

In [167]:
## Exploratory Data Analysis (EDA)

# 1. Missing Values Analysis
print("="*50)
print("MISSING VALUES ANALYSIS")
print("="*50)
missing_data = df.isnull().sum()
missing_percent = (df.isnull().sum() / len(df)) * 100
missing_df = pd.DataFrame({'Missing_Count': missing_data, 'Percentage': missing_percent})
print(missing_df[missing_df['Missing_Count'] > 0])
print("\n")

==================================================
MISSING VALUES ANALYSIS
==================================================
              Missing_Count  Percentage
Status                  146   14.747475
Opening date            183   18.484848
Manufacturer             58    5.858586
latitude                207   20.909091
longitude               207   20.909091
opening_date            183   18.484848
speed_mph               140   14.141414
height_ft               831   83.939394
G-force                 666   67.272727

In [ ]:
# 2. Statistical Summary of Numeric Columns
print("="*50)
print("STATISTICAL SUMMARY - NUMERIC COLUMNS")
print("="*50)
print(df.describe().round(2))
print("\n")

In [ ]:
# 3. Categorical Data Analysis
print("="*50)
print("CATEGORICAL DATA ANALYSIS")
print("="*50)
categorical_cols = ['Status', 'Type_Main', 'Manufacturer']
for col in categorical_cols:
    print(f"\n{col} - Value Counts:")
    print(df[col].value_counts())

In [ ]:
# 4. Correlation Analysis
print("="*50)
print("CORRELATION ANALYSIS")
print("="*50)
numeric_cols = df.select_dtypes(include=['float64', 'int64']).columns
correlation_matrix = df[numeric_cols].corr()
print(correlation_matrix.round(3))

In [ ]:
# 5. Correlation Heatmap
plt.figure(figsize=(10, 8))
sns.heatmap(correlation_matrix, annot=True, fmt='.2f', cmap='coolwarm', center=0)
plt.title('Correlation Heatmap - Numeric Variables')
plt.tight_layout()
plt.show()

In [ ]:
# 6. Distribution of Numeric Variables
fig, axes = plt.subplots(2, 3, figsize=(15, 10))
fig.suptitle('Distribution of Numeric Variables', fontsize=16, fontweight='bold')

numeric_columns = ['year_introduced', 'speed_mph', 'height_ft', 'Inversions', 'G-force', 'latitude']
for idx, col in enumerate(numeric_columns):
    row = idx // 3
    col_pos = idx % 3
    # Handle NaN values
    data_clean = df[col].dropna()
    axes[row, col_pos].hist(data_clean, bins=30, edgecolor='black', alpha=0.7)
    axes[row, col_pos].set_title(f'{col}')
    axes[row, col_pos].set_xlabel(col)
    axes[row, col_pos].set_ylabel('Frequency')

plt.tight_layout()
plt.show()

In [ ]:
# 7. Categorical Variables Visualization
fig, axes = plt.subplots(1, 3, figsize=(16, 5))
fig.suptitle('Categorical Variables Distribution', fontsize=16, fontweight='bold')

categorical_cols = ['Status', 'Type_Main', 'Manufacturer']
for idx, col in enumerate(categorical_cols):
    top_values = df[col].value_counts().head(10)
    axes[idx].barh(range(len(top_values)), top_values.values)
    axes[idx].set_yticks(range(len(top_values)))
    axes[idx].set_yticklabels(top_values.index)
    axes[idx].set_title(f'{col} (Top 10)')
    axes[idx].set_xlabel('Count')
    axes[idx].invert_yaxis()

plt.tight_layout()
plt.show()

In [ ]:
# 8. Box Plots for Numeric Variables
fig, axes = plt.subplots(2, 3, figsize=(15, 10))
fig.suptitle('Box Plots - Numeric Variables', fontsize=16, fontweight='bold')

numeric_columns = ['year_introduced', 'speed_mph', 'height_ft', 'Inversions', 'G-force', 'latitude']
for idx, col in enumerate(numeric_columns):
    row = idx // 3
    col_pos = idx % 3
    data_clean = df[col].dropna()
    axes[row, col_pos].boxplot(data_clean)
    axes[row, col_pos].set_title(f'{col}')
    axes[row, col_pos].set_ylabel('Value')

plt.tight_layout()
plt.show()

In [ ]:
# 9. Coaster Introduction Trends Over Time
fig, ax = plt.subplots(figsize=(14, 6))
coasters_per_year = df['year_introduced'].value_counts().sort_index()
ax.plot(coasters_per_year.index, coasters_per_year.values, marker='o', linewidth=2, markersize=4)
ax.set_title('Number of Coasters Introduced Over Time', fontsize=14, fontweight='bold')
ax.set_xlabel('Year')
ax.set_ylabel('Number of Coasters')
ax.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

print("\nCoasters per Year Summary:")
print(coasters_per_year.describe())

In [ ]:
# 10. Key Insights Summary
print("="*60)
print("KEY INSIGHTS FROM COASTER DATA")
print("="*60)
print(f"Total Coasters: {len(df)}")
print(f"Year Range: {df['year_introduced'].min()} - {df['year_introduced'].max()}")
print(f"\nAverage Speed: {df['speed_mph'].mean():.2f} mph")
print(f"Fastest Coaster: {df['speed_mph'].max():.2f} mph")
print(f"Average Height: {df['height_ft'].mean():.2f} ft")
print(f"Tallest Coaster: {df['height_ft'].max():.2f} ft")
print(f"Average G-force: {df['G-force'].mean():.2f}G")
print(f"Maximum G-force: {df['G-force'].max():.2f}G")
print(f"\nMost Common Type: {df['Type_Main'].value_counts().idxmax()}")
print(f"Status Distribution:\n{df['Status'].value_counts()}")
print(f"\nTop 5 Manufacturers:")
print(df['Manufacturer'].value_counts().head())